version: "3.7"
services:

  apache:
    build:
      context: docker/apache
    volumes:
    - ./app:/var/www/html
    ports:
    - 8081:80

  php-cli:
    build:
      context: docker/php-cli
    volumes:
    - ./app:/var/www/html
    user: 1000:1000
